//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssesmentApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class adtrack_test
    {
        public int Id { get; set; }
        public string TimeStamp { get; set; }
        public string PlatformType { get; set; }
        public string DeviceModel { get; set; }
        public string ImageName { get; set; }
        public string ImageUrl { get; set; }
        public int UserId { get; set; }
        public string CompanyId { get; set; }
        public string BrandName { get; set; }
        public string Name { get; set; }
        public bool is_youtube { get; set; }
        public string GDriveLink { get; set; }
        public string DestinationLink { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string category_name { get; set; }
        public string advertiserName { get; set; }
        
    }
}
